### ISSUE TITLE
quasar test -u gives error after clean install

### ISSUE THREAD

**Issue by beebase** [rstoenescu/quasar-framework#101]
I'm getting this error after initialising a new project with quasar and running a unit test
![image](https://cloud.githubusercontent.com/assets/446089/18788263/7d077348-81a6-11e6-9853-d890bb5e0f94.png)

**Comment by rstoenescu** [comment]
Oops, forgot about that. Just replace or delete the test case file in there.

**Comment by rstoenescu** [comment]
Fixed. I think some more thinking needs to be put for testing with vue-router though. Need some help here.

**Comment by beebase** [comment]
I haven't written lots of tests yet but I'm determined to have my current project properly covered with tests
Will share once I've got something decent running

**Comment by rstoenescu** [comment]
Great. Looking forward to it!
