### ISSUE TITLE
question: where to put customFont.ttf ?

### ISSUE THREAD

**Issue by beebase** [rstoenescu/quasar-framework#105]
Forgive me if I overlooked it in the docs (great source!), but how/where should I put custom fonts?
Should I use fontface in css like this?
```
@font-face {
    font-family: 'DevilBreezeBold';
    src: url('??/DevilBreezeBold.ttf') format('truetype');
    /* Chrome 4+, Firefox 3.5, Opera 10+, Safari 3—5 */
  }
```

**Comment by musicformellons** [comment]
@beebase In `project/src/themes/app.variables.styl   `  you can put:
$typography-font-family = 'Arial', '-apple-system', 'Helvetica Neue', Helvetica, Arial, sans-serif

That will use this font for both android and ios. If you want different fonts for each then put it in the respective stylus sheet in the same folder.

**Comment by beebase** [comment]
Thanks for clarifying. But shouldn't I put the font.ttf file in some specific directory?
One other thing. The other day I was changing some colors like $primary in app.variables.styl but the changes aren't visible (chrome browser and quasar play) when restarting with "quasar dev". Is there some cache that needs to be cleared?

**Comment by musicformellons** [comment]
Yeah, probably Razvan can tell you where best to put your .ttf file. 

When you customize you need to follow the instruction in comments of the app.js file:
/*
 If overriding Quasar style, leave uncommented
 just the first line.
 If NOT overriding Quasar style, leave uncommented
 just the second line. This option make compiling faster.
 WARNING!
 Leave just one of the two require() calls below
 uncommented.
 */

**Comment by rstoenescu** [comment]
Quasar leaves that to you to organize files however you want. But I think you are referring to "if I use this URL where should I put the font file". This is where Webpack comes into play. It automatically bundles your dependencies (even fonts!). Let's say we specify @font-face in `src/themes/app.variables.styl` with `src url(DevilBreezeBold.ttf)`. Then Webpack will look for  `DevilBreezeBold.ttf` file in the same folder (`src/themes/`) and add it to the bundle. The URL is parsed as being a relative path to the same folder of your CSS/Sass/SCSS/Stylus file where you declare it. Let me know if you need more clarifications.

**Comment by beebase** [comment]
ah of course. Thanks for your explanation.
I did "scan" that styling message in the app.js a couple of times but it didn't really sink in, cause I didn't need it while exploring the fun stuff (components!!) . 
"yeah, we'll deal with styling later on...." ;-)
So I just didn't take the time to understand what was being said. 

Maybe that message could also be made a bit more clear along something like the following lines?

```
// === DEFAULT / CUSTOM STYLE ===
// WARNING! always comment out ONE of the two require() calls below.
// 1. use next line to activate CUSTOM STYLE (./src/themes)
require('./themes/app.' + __THEME + '.styl')
// 2. or, use next line to activate DEFAULT QUASAR STYLE
// require('quasar/dist/quasar.' + __THEME + '.css')
// ===========================
```
(And maybe more importantly: in the app.variables.style, refer to the app.js as a reminder)

**Comment by rstoenescu** [comment]
Thank you for the suggestion! Made the changes you proposed to the starter kit.

**Comment by beebase** [comment]
To everyone figuring out custom fonts (and a bit of stylus),
...I believe customizing works pretty well ;-)

![img2309](https://cloud.githubusercontent.com/assets/446089/18851189/1b091268-843b-11e6-9b0b-62f4d16c905d.jpg)

font location
![img2311](https://cloud.githubusercontent.com/assets/446089/18851245/48e27648-843b-11e6-817e-074d386b27a4.jpg)

declare in app.variables.styl
![img2316](https://cloud.githubusercontent.com/assets/446089/18851277/7a432cd2-843b-11e6-889c-ee4dcbb0feef.jpg)

webpack bundling
![image](https://cloud.githubusercontent.com/assets/446089/18851433/3cfc3f48-843c-11e6-8d46-1b6e20c65485.png)

reference in vue component style
![image](https://cloud.githubusercontent.com/assets/446089/18851406/231dcb78-843c-11e6-89a6-55e8b951dc7a.png)

**Comment by rstoenescu** [comment]
Haha, nice one with the first screenahot. Made my day :D Would you care to post your last comment on the forum under Show & Tell?
Glad I could help.

**Comment by beebase** [comment]
http://forum.quasar-framework.org/topic/14/add-custom-fonts-to-your-app

**Comment by rashnk** [comment]
it does not work for me 

i copied font file to themes/fonts

//app.variables.styl
```
@font-face 
    font-family myfont
    src url(fonts/Chilanka-Regular.ttf)
```



```
//Index.vue
<style>
.myclass {
  font-family: myfont;
  font-size: 30px
}
```
</style>


whe use my class to an element, the font does not change

**Comment by beebase** [comment]
Are you using correct spacing? Indentation is important with .styl files. 
Try this link to verify your .styl
http://stylus-lang.com/try.html

**Comment by rashnk** [comment]
solved , i forgot to uncomment the custom style refrence in main.ts

**Comment by disarticulate** [comment]
is this still valid? 

quasar -v 0.15.20

 ERROR  Failed to compile with 9 errors                                                       17:34:34

This relative module was not found:
```
* ./fonts/courier-new-webfont.ttf in ./node_modules/css-loader??ref--12-1!./node_modules/postcss-loader/lib??ref--12-2!./node_modules/stylus-loader??ref--12-3!./.quasar/app.styl, ./node_modules/css-loader?{"minimize":false,"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/stylus-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/dataTable/tablesPageNavigation.vue and 7 others
```

**Comment by venkyvb** [comment]
This works if I update the app.styl file (under the /css/ folder), with the @font-face definition and set the  $typography-font-family to reflect the new font families.
