### ISSUE TITLE
Any chance of hooking in Quasar with GraphQL?

### ISSUE THREAD

**Issue by smolinari** [rstoenescu/quasar-framework#11]
I really like the work being done here. 

Has there been any thought to hook GraphQL communications to the server to get persisted state with Quasar?

Scott

**Comment by rstoenescu** [comment]
Thanks for the appreciation!

You can include GraphQL in your application as a dependency. I saw they have an NPM package that you can install for the client side (https://www.npmjs.com/package/graphql) to import a dependency here: http://quasar-framework.org/guide/importing-dependencies.html

It would be best to hold on for the next update to Quasar which will add Babel support and a brand new build system for even better speed and (besides many other advantages) making the importing a dependency super easy. `vue-loader` is also on the table.

**Comment by smolinari** [comment]
Sounds good. My "dream" is more about getting GraphQL to jive with Vuex. I've been following a couple of other projects, namely [Apollo](https://github.com/apollostack/apollo-client) and [Meteor-Vue-Component](https://github.com/Akryum/meteor-vue-component). Apollo is made specifically for GraphQL, but it doesn't yet work with Vue and they use Redux as the store, which isn't the best way to jive with Vue from what I understand, although Vue 2.0 should do better with Redux. And the meteor-vue-component only works with Meteor, from what I understand. So, that's a no-go for me.

If Quasar could work directly with Apollo, through Vuex, that would be the dream come true for me. :smile: 

At any rate. Thanks for listening and responding.

Scott

**Comment by rstoenescu** [comment]
I see. Well, for the time being, Quasar 0.4.0 has Vuex installed by default. You can npm install `apollo-client` and/or `graphql` and use them. Make sure you tell Quasar that you'd like them included (see the Importing Dependencies link I posted earlier). Basically you can use ANY front-end libs you like with Quasar.

After the next big update (that I'm currently working on), managing ANY dependency will be super easy and straightforward and way simplified.

Razvan

**Comment by smolinari** [comment]
Great. And I'll hit the books some more. 

Is there a way I can reach you privately by chance? 

Scott

**Comment by rstoenescu** [comment]
You got my email on https://github.com/rstoenescu

**Comment by smolinari** [comment]
Hey Razvan @rstoenescu ,

Just FYI.

https://github.com/Akryum/vue-apollo

And Akryum said he'll be working on a vuex implementation too. 

Yes!!!!

Scott

**Comment by rstoenescu** [comment]
That's great!!! Thx for letting me know.
