### ISSUE TITLE
Mobile browser addressbar color

### ISSUE THREAD

**Issue by rstoenescu** [rstoenescu/quasar-framework#114]
![6ishfm](https://cloud.githubusercontent.com/assets/4665641/18983399/2e672bee-86f5-11e6-8964-0b49de0851cf.png)

The browser addressbar color should be the primary color.

How to do it without tampering with the build system or touching Stylus files: In `src/themes.js` (maybe later will move the logic to some other file):

1. Check if running on a mobile browser (`import Platform from './platform'): `if Platform.is.mobile && !Platform.is.cordova`

2. Add an absolute positioned DOM element to `<body>` outside of the viewport (like top -10000px) with `bg-primary` CSS class. Also give it some height like `10px`.

3. Use `window.getComputedStyle(<ELEMENT from above>).getPropertyValue('background')` to retrieve the color -- which will be the primary color.

4. Remove the absolute positioned DOM element.

5. Add the meta tag to `<head>` using the color determined at step #3.

**Comment by vuchl** [comment]
I'll implement that over the weekend!

**Comment by vuchl** [comment]
#118

**Comment by rstoenescu** [comment]
Thank you for implementing this! Great work!

**Comment by ag-coder** [comment]
Where can i set just the "apple-mobile-web-app-status-bar-style" to black?

**Comment by rstoenescu** [comment]
@ag-coder Hmm, guess this needs a little bit of enhancement. It currently sets it same as your primary color.

**Comment by ag-coder** [comment]
Set it direct in the index.html will not work right? Can you give me a hint where i have to enhance it?
thanks

**Comment by rstoenescu** [comment]
@ag-coder Can you open up a new Github ticket for this pls? "Enhance mobile browser address bar coloring". I'll start working on it right now. Will make this optional so every developer can choose to color the addressbar with primary color (default) or another color, or opt out of coloring the address bar. Thanks!
