### ISSUE TITLE
Improved multi select dropdown for desktop

### ISSUE THREAD

**Issue by Async0x42** [rstoenescu/quasar-framework#117]
In a desktop view, the '<selection> and one/two/three more' could be used to display more info to the user. 

If you take a look here: http://element.eleme.io/#/component/select (and find in page for '基础多选' ), you'll see that the multi select dropdown they have is able to display multiple values. For a desktop-based site this would be a really great option to have instead of the current mobile-focused dropdown.

**Comment by rstoenescu** [comment]
You can use the "placeholder" property to display whatever you like. Make your own through a computed property: `:placeholder="computedPlaceholder"`. Pseudocode for computedPlaceholder:

if model is empty
  then return 'Choose a color'
else
  return model[0] + ', ' + model[1] + ....

Will also take this into consideration for the next Quasar version.

**Comment by rstoenescu** [comment]
I think can be closed. Selects have evolved a lot lately. Please reopen if you think something can still be improved.
