### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by spekulatius** [rstoenescu/quasar-framework#12]
Hello @rstoenescu 

would you been interested in setting up quasar on https://www.bountysource.com/ ? I'd like to contribute a bit :)

Cheers,
Peter

**Comment by rstoenescu** [comment]
Thank you so much, Peter!

I've been working hard on this framework for almost a year now on my own money. Any help is highly appreciated!

I've set up a page on Bountysource: https://salt.bountysource.com/teams/quasar-framework

On the website there is also a "Support Quasar" link which leads to this page: http://quasar-framework.org/support-quasar-framework.html

**Comment by spekulatius** [comment]
Hello Razvan,

I have put some help on. I'll leave it on for at least a year :)

Cheers,
Peter

**Comment by rstoenescu** [comment]
Thank you for your generous support!

Watch out for the next release that I'm working on. It will bring new faster build system & CLI, ES6, vue-loader support, hot reload, just to name a few novelties.

Follow me on Twitter @quasarframework for updates.

Big thanks again!

**Comment by spekulatius** [comment]
Hey Razvan,

no worries. I'm happy to contribute and very keen to see where the journey is taking quasar. Yay, CLI, es6 and vue-loader are pretty much the things I'm using / would use :)

Still need to find time to proper dive into quasar by doing an example project. I'll keep you posted :)

Peter

**Comment by rstoenescu** [comment]
For now I would suggest just diving through the documentation (specifically for the Web Components and API which will remain the same in the next version) as the architecture will suffer heavy breaking changes (needed improvements).

-Razvan

**Comment by IniZio** [comment]
Great to see a big release coming! Which version of vue will the new version use though?

**Comment by rstoenescu** [comment]
Next Quasar will be based on 1.x too.
There are plans to upgrade to 2.x once Vue gets out of beta.
