### ISSUE TITLE
List Multi-Line wrong presentation ?

### ISSUE THREAD

**Issue by pici** [rstoenescu/quasar-framework#120]
i do not get a correct presentation of my multi-line list.
here my code and a screen picture.
Any ideas ?
```
`<template>
  <quasar-layout>
  <div>
    <div class="layout-padding">
      <p class="caption">Primary</p>
        <div class="list item-inset-delimiter">
          <div class="item">
            <i class="item-primary">assignment_ind</i>
            <div class="item-content has-secondary">Icon as Primary</div>
          </div>
          <div class="item">
            <i class="item-primary">mail</i>
            <div class="item-content has-secondary">
              <div>Avatar as Primary</div>
              <div>test 2nd</div>
            </div>
          </div>
          <div class="item">
            <i class="item-primary">assignment_ind</i>
            <div class="item-content has-secondary">Thumbnail as Primary</div>
          </div>
          <div class="item">
            <div class="item-primary">Q</div>
            <div class="item-content">One character as Primary</div>
          </div>
        </div>
    </div>
  </div>
</quasar-layout>
</template>`
```
![bildschirmfoto 2016-10-05 um 11 20 38](https://cloud.githubusercontent.com/assets/1688963/19109696/618d4ac4-8aee-11e6-8902-fae5aa622324.png)

**Comment by rstoenescu** [comment]
You're using one-line items there. Any particular CSS breaking Quasar's one?

**Comment by rstoenescu** [comment]
Couple of things to fix on your template:

1. Remove 'has-secondary' from all your items. You don't have secondaries.

2. Add 'two-lines' class to the following two-lines item:
``` html
          <div class="item">
            <i class="item-primary">mail</i>
            <div class="item-content has-secondary">
              <div>Avatar as Primary</div>
              <div>test 2nd</div>
            </div>
          </div>
```

And make your you don't have any CSS in your app interfering with Quasar's one regarding lists and items. Please reopen if problem persists. Thanks!

**Comment by rstoenescu** [comment]
Also, are you using v0.7 or v0.6. I have a hunch you're on v0.6. Lists have been completely redesigned in v0.7.

**Comment by pici** [comment]
Thanks for your help. Everything is working now.
I figured out that my old npm didn't updated quasar-framework.
Updated npm and quasar. Everything fine.

Great Work !

brgds pici

**Comment by rstoenescu** [comment]
Great! Glad I could help.
