### ISSUE TITLE
Vue-Head / Vue-Helmet compatibility

### ISSUE THREAD

**Issue by Keidrych** [rstoenescu/quasar-framework#125]
I'm trying to control each part of the SPA's metadata, and page title, as possible on https://github.com/joshbuchea/HEAD.

There are 2 Vue optimized libraries: [Vue-Head](https://github.com/ktquez/vue-head) & [Vue-Helmet](https://github.com/miaolz123/vue-helmet) that are designed for this. Vue-Head is in my understanding the more flexible of the two as it supports social graph as well.

Really loving Quasar, its such a well integrated package, but when using Quasar + Vue Head, the actual Vue-Head component becomes totally disabled and unable to update the page meta & title information.

From my initial debugging, it looks like its partly to do with the way the index file is structured, but then if you insert Vue-Head before Quasar.use, Quasar breaks entirely so a load order dependency seems to be causing a conflict. 

Any ideas?

**Comment by rstoenescu** [comment]
Will investigate to see what's going on.

**Comment by rstoenescu** [comment]
Can you please explain how Quasar is broken by Vue-Head? Any error messages? I bet it's the CSS that doesn't gets loaded? This is because Webpack itself injects CSS into the head of the document. If Vue-Head interferes and removes it then we have a problem. Please detail your case.

Thanks for logging this issue.

**Comment by rstoenescu** [comment]
Can you put together a simple repo to see the issue, please? It would help a lot!

**Comment by Keidrych** [comment]
Done, this 'should' load the view in the framework, search out the <head> components and update them.

As you can see from execution, nothing is being updated anywhere, and the update event isn't firing. Its as code isn't being executed at all.

[https://github.com/Keidrych/head-testing.git](https://github.com/Keidrych/head-testing.git)

**Comment by rstoenescu** [comment]
Well, first thing that I see is that `itStarts.vue` isn't connected to any route. And that's where you use Vue-Head. In `src/router.js` you only specify two routes, one for 404 and default for `index.vue`:

``` js
let routes = {
  // Not found
  '*': {
    component: load('error404')
  },

  // Default
  '/': {
    component: load('index')
    /*
    subRoutes: {
    }
    */
  }
}
```

Add `itStarts` somewhere. In my case I just replaced `load('index')` with `load('itStarts')`. And vue-head worked. It updated everything. Screenshot attached:

![screenshot from 2016-10-11 09 52 08](https://cloud.githubusercontent.com/assets/4665641/19261262/95bca656-8f98-11e6-884d-ac7263ea368a.png)

**Vue-Head is perfectly compatible with Quasar.**

Please reopen if I missed something.

**Comment by Keidrych** [comment]
-.- dang so sorry, I totally missed that in my checking through the points. Thank you for the help & second set of eyes

**Comment by rstoenescu** [comment]
Glad I could help!
