### ISSUE TITLE
authentication feature

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#126]
Maybe include jwt & oauth2 authentication? This seems to become more mature e.g.:
https://github.com/websanova/vue-auth

**Comment by rstoenescu** [comment]
Well, if there is such a package already dealing with this, why not use this instead of reinventing the wheel? What would be the benefit of Quasar's own jwt and oauth2 authentication?

**Comment by dobromir-hristov** [comment]
Currently using vue-auth with the framework. Apart from my backend giving me funky results, it works flawlessly.

**Comment by musicformellons** [comment]
@rstoenescu I see your point. I would be more like a 'plugin' for the really lazy among us I suppose. Feel free to close this. @dobromir-hristov I will see if I can get it up properly as well.
