### ISSUE TITLE
installing vue-chartist

### ISSUE THREAD

**Issue by beebase** [rstoenescu/quasar-framework#128]
I'm trying to make vue-chartist work  in a quasar app but webpack doesn't seem to load the css that comes with vue-chartist.

Should I put the chartist files in a particular directory or should the webpack config be customized?

https://github.com/Yopadd/vue-chartist

**Comment by dobromir-hristov** [comment]
Looking at their code, they require chartist directly inside the Vue-chartist component, but not the css it self. I think you have to require it inside your components manually.

**Comment by vuchl** [comment]
From what I can see, the vue-chartist plugin does not even come with css. And from their website https://gionkunz.github.io/chartist-js/getting-started.html#one-two-three-css
you need to link the stylesheet in the head of your index.html. So use a CDN version maybe.

**Comment by rstoenescu** [comment]
Are you building a Mobile app, just a website or both?

If just a website, then include that CDN link (to Chartist CSS) into the head of your `index.html` and you're good to go.
If also building a Mobile app, then `npm install --save chartist` and import `chartist/dist/chartist.min.css` from somewhere (maybe `app.js`).

**Comment by dobromir-hristov** [comment]
Nah, CDN is not the "ideal" solution in the current days of Webpack, one file for all etc...
Chartist has a css in its dist folder. Look for it in `node_modules/chartist/dist'
