### ISSUE TITLE
Stylus vars inside components

### ISSUE THREAD

**Issue by dobromir-hristov** [rstoenescu/quasar-framework#129]
Is it a bad practice to require the stylus vars file to be able to use the colors from inside a component?

**Comment by rstoenescu** [comment]
Certainly not. You can do it care-free :)

**Comment by vuchl** [comment]
How would one do that anyway? Just curious.

**Comment by dobromir-hristov** [comment]
Use the forum link provided above :)

**Comment by rstoenescu** [comment]
Thanks for moving this to the forum, Dobromir! I appreciate it!
