### ISSUE TITLE
Default templates

### ISSUE THREAD

**Issue by pablohenrique** [rstoenescu/quasar-framework#13]
Does quasar has any default template like ionic ($ ionic start myApp tabs)?

I hope to help you guys soon. I'm in love with VueJS and I'll try quasar today.

**Comment by rstoenescu** [comment]
Hi,

Yes, Quasar has a CLI too. First NPM install globally quasar-cli then read here: http://quasar-framework.org/guide/create-app.html

Only thing to notice is that Quasar is undergoing major changes to support ES6, vue-loader, smarter starter boilerplate, hot reload, e2e testing, faster build times, smaller footprint, new and faster CLI and many more! v0.5.0 coming soon. See "dev" branch for progress.

This new version is scheduled to be released in less than 2 weeks. It's a game changer. Stay tuned and if you can help out I'd be more than thrilled. You can also contact me by email. I am going to start a team on Quasar very soon.

-Razvan

**Comment by pablohenrique** [comment]
Goddam! Thank you!!! I can't wait for it.
