### ISSUE TITLE
Cannot use stacked labels with select

### ISSUE THREAD

**Issue by dobromir-hristov** [rstoenescu/quasar-framework#132]
Because the Select box has a label inside its dialog box, and the `stacked-label` element styles all labels, there is a bit of an issue with using them both. 

Fix:
First way is to add a class to the label in the `stacked-label` element so we don't style all labels inside it.
Second way is to add a `:not()` to the `stacked-label` so we don't style labels from the `quasar-popover-content` element.
Third way remove the `label` element from the `select` element's dialog altogether.  

Don't know if there is room for this in the 0.8 release.

**Comment by dobromir-hristov** [comment]
Ok so its not only css, because clicking on the labels doesn't trigger a change, I guess there is an issue with the event bindings as well.

**Comment by rstoenescu** [comment]
Can you screenshot it here, pls?

**Comment by dobromir-hristov** [comment]
What would you like me to screenshot? I managed to overwrite the css that broke the dialog`s visibility (all labels were absolute) but upon clicking on one of the select choices, the dialog doesn't close.

**Comment by rstoenescu** [comment]
Without any CSS overwrites, pls screenshot your select with stacked labels and copy-paste your HTML for it here.

**Comment by dobromir-hristov** [comment]
```html
<div class="stacked-label">
              <quasar-select
                type="radio"
                :model.sync="tempSettings.temperature_mode"
                :options="temperature_options"
              ></quasar-select>
              <label> Temperature Mode </label>
            </div>
```
![quasar app](https://cloud.githubusercontent.com/assets/9863944/19434804/33d7f40e-9470-11e6-9720-93f589c88d9d.png)

**Comment by dobromir-hristov** [comment]
Z-index was the issue here.
```css
.stacked-label label, .floating-label label {
...
z-index:-1;
...
}
```

**Comment by rstoenescu** [comment]
Oh, I now see. I had an entirely different picture in mind. Anyway, haven't written these stacked labels to work with select. They work with input textboxes and textareas only. It's anyway pointless to use a stacked-label div with a select as it doesn't add any benefits like with an input textbox. Simply write your own HTML markup which incorporates a select.

Will consider how this can be improved in the future though.

**Comment by dobromir-hristov** [comment]
I just wanted to be consistent :) It works OK now though.

**Comment by rstoenescu** [comment]
I plan on writing some form CSS classes in the future which will be of great help in scenarios like yours ;)
