### ISSUE TITLE
Building android

### ISSUE THREAD

**Issue by jjsquad** [rstoenescu/quasar-framework#14]
transformClassesWithDexForArmv7DebugException in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0

How can I solve this error?

Thanks

**Comment by rstoenescu** [comment]
Hmm. Please open up a bug on Cordova's github. This is completely outside of Quasar. Unfortunately got no idea how to help you with this Cordova issue. Try deleting the "cordova" folder, update to latest cordova version, and then wrap your Quasar app again. Maybe this fixes it.
