### ISSUE TITLE
Quasar version command outputs 0.2.0

### ISSUE THREAD

**Issue by laurentpayot** [rstoenescu/quasar-framework#140]
With Quasar v0.8 I get:
```
~$ quasar -V

0.2.0
```

**Comment by rstoenescu** [comment]
Yes. That's the CLI version, not the Quasar version you are using.

**Comment by laurentpayot** [comment]
Ok but how can I know the Quasar version I'm using then? (0.7 or 0.8)

**Comment by rstoenescu** [comment]
`npm ls quasar-framework`

or at runtime:

``` js
import Quasar from 'quasar'

console.log(Quasar.version)
```

**Comment by laurentpayot** [comment]
D'oh! Obviously. Thanks.
