### ISSUE TITLE
Component proposal: CONFIRMATION MODAL

### ISSUE THREAD

**Issue by mariaczi** [rstoenescu/quasar-framework#141]
Hi,

I would like to propose component implementation.
Confirmation modal basically is extending the modal component but with out-of-box wrapper for accept/deny/cancel.
It is really nice with KeenUI - https://josephuspaye.github.io/Keen-UI/#/ui-confirm-docs - and I think it would be great addition to Quasar!

**Comment by rstoenescu** [comment]
Already in.
http://quasar-framework.org/components/dialog.html#Confirm-Example
