### ISSUE TITLE
ERROR in ./~/quasar-framework/dist/quasar.common.js

### ISSUE THREAD

**Issue by ystreibel** [rstoenescu/quasar-framework#143]
Hi,

I would like to create a first application by using quasar-cli :

`$ quasar init v2 my-project`
`$ cd my-project`
`# edit package.json`
`$ npm install`
`$ quasar dev`

In console, I have this error when I'm launching quasar dev command : 

`ERROR in ./~/quasar-framework/dist/quasar.common.js`
`Module not found: Error: Cannot resolve module 'hammerjs' in /my-project/node_modules/quasar-framework/dist`
` @ ./~/quasar-framework/dist/quasar.common.js 13:29-48`

What could I do ?

**Comment by rstoenescu** [comment]
Thanks for pointing this out!! Published a few hours ago 0.7.1 which overwrote the latest version which was 0.8.2. Republished with v0.8.3. It will work now.
