### ISSUE TITLE
Upgrade Wiki

### ISSUE THREAD

**Issue by obonyojimmy** [rstoenescu/quasar-framework#145]
Hi , thanks to this awesome framework , i however noticed that its now being upgraded to version using version 2 , a wiki on upgrade would be appropriate.

**Comment by rstoenescu** [comment]
Just follow the release notes https://github.com/rstoenescu/quasar-framework/releases/tag/v0.8.0
And of course, the vue migration guide. Will add a page to the doc as time allows, but the release notes should cover for the moment. Working 18-20 hours a day, hope I don't go mad :)

**Comment by obonyojimmy** [comment]
@rstoenescu id like to help out am currently free and am good in ui dev + vue + laravel kindly contact me cliffjimmy27@gmail.com

**Comment by rstoenescu** [comment]
Sent you an email. Thanks for wanting to join the party!
