### ISSUE TITLE
Floating label not working

### ISSUE THREAD

**Issue by mariaczi** [rstoenescu/quasar-framework#147]
Hi,

I am just starting conversion from old components to quasar.
Just created input with floating label

```
<div class="floating-label">
  <input required class="full-width">
  <label>Floating Label</label>
</div>
```
And it is not working... There is label and input but not floating...

**Comment by rstoenescu** [comment]
Absolutely nothing has changed for floating labels. Check if any of your App's CSS is tempering with inputs or labels.

**Comment by rstoenescu** [comment]
You can also check that floating labels work here on Quasar Play app: http://quasar-framework.org/quasar-play/android/index.html#/showcase/form/text-input/textbox

Make sure you're running latest v0.8.3. Please reopen if something is indeed wrong and needs fixing. A screenshot may help. Thanks!

**Comment by mariaczi** [comment]
I did uograde to 0.9 today.
I did not add any css yet

28 paź 2016 22:24 "Razvan Stoenescu" <notifications@github.com> napisał(a):

**Comment by rstoenescu** [comment]
0.9 hasn't been released yet :) It's under an npm tag and beta but nobody knows about it :)
Use v0.8.3

**Comment by mariaczi** [comment]
@rstoenescu LOL. It is automatically downloading by npm update... 

I found the issue with floating! It is working only with `required` ! When there is required, it is working fine, but without it it is standard label. Can you fix it?

BTW. Would there be any issue to use materializeCSS with Quasar? Don't want to get conflicts..

**Comment by rstoenescu** [comment]
Must be an npm issue. Unpublished that tag.

Anyway, regarding the floating label: yeah, works only with `required`. I won't go into technical details, but due to current state of CSS, it really can't work without that attribute. It can be done through a component but that is too much overhead!

I get this often. Can I use X css framework with Quasar. Basically you can but may get into trouble. But my question is: why would you use any other CSS framework with Quasar when Quasar supplies everything (and in most cases much more) with its own CSS framework? What do you think Quasar misses when compared to Materialize? Or is it a problem with the documentation in that it needs to be more clear?

**Comment by mariaczi** [comment]
@rstoenescu Any work around to get floating for non-required fields? I understand background but it will be silly when on not required fields I will have standard label... 

I think it is mater of documentation, you're right. Quasar is awesome and I think you will make it even better with time (just keep backward compatibility please!). E.g. grid with materialize was going like storm, but with current grid documentation for quasar I am struggling with this simple thing.
`s12 m6 l4` is really convinient way to be honest which I can't find with Quasar yet.

**Comment by rstoenescu** [comment]
API had to change some parts of it when upgrading to use Vue 2. There's no other way.
Anyway, API will very soon stabilize and we'll enter the first beta stage for 1.0.

Regarding `s12 m6 l4`. I just checked the documentation, and indeed it needs an improvement on clarity for Grid CSS. You have those `width-XofY` classes that you can use. Put a `sm`, `md`, `bg`, `lg` in front of that CSS classes and there you have it! Full list of prefixes: http://quasar-framework.org/api/css-grid-layout.html#Visibility
You also have offset CSS classes. The documentation states (in the link above): "The following list displays prefixes (can be used as standalone too!) that you can use for all of the above CSS classes."

Will make it more clear. Thanks for your feedback!

**Comment by rstoenescu** [comment]
One more thing: Making input field "required" doesn't force that field to actually need to be filled in. We're not using `<form>`s anymore, so you decide on how you do validation (vee-validate as recommended option) and how you use the input field values to send information to the backend.

**Comment by rstoenescu** [comment]
I guess I will have to create a component for cases when you use forms and must avoid required.
