### ISSUE TITLE
Can you document browser(version) support?

### ISSUE THREAD

**Issue by otabekgb** [rstoenescu/quasar-framework#148]
I could not find browser support info on your sites. Can you document that?

**Comment by rstoenescu** [comment]
Will do soon. Supported browsers are Chrome, Firefox, IE11+ (will add support for IE9 and IE10 soon), Edge, Safari 9.1+, Opera, Android browser 4.4+. Moving this issue to quasar-site repo since it's a matter of documentation.

**Comment by vuras** [comment]
Hello, will IE9/IE10 support ever be added?

**Comment by rstoenescu** [comment]
Hello, due to too many missing web standards, IE9/10 will not be added.
Sorry for any inconvenience.
