### ISSUE TITLE
Improvements needed for Range component

### ISSUE THREAD

**Issue by robmpreston** [rstoenescu/quasar-framework#15]
1) While clicking and dragging the slider around, the value in the model should update (right now it only updates after releasing)
2) Slider should have a 'step' value i.e. min- 0, max- 100, step- 10 would go 0,10,20,30...etc

I think it would also be nice if instead of the current style, it "fills up" as you drag it, i.e. the right side of the slider is grey and the selected portion is blue

**Comment by rstoenescu** [comment]
Planning on releasing new Range component with requested functionality soon.

**Comment by rstoenescu** [comment]
Pushed commit to enhance Range component:

commit 76e9f3ae97ad35e0059210d4ca2af04ac9628fe9
Date:   Thu Aug 18 18:20:21 2016 +0300

    refactor: Rewritten Range to support new features
    
    + "step" property
    + colored styles
    + markers
    + "snap" property
    + "label" property

Will be available in v0.5.1 in a few days.
