### ISSUE TITLE
quasar-tab target property should also takes HTMLElement values

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#17]
Quasar-tab component currently takes a "target" property, of type String, which value is a "DOM element selector for target" (identify the content tab element associated with this tab).
It would be better if it also takes a HTMLElement value, it lets us reference the tab content elements using the v-el directive, which is cleaner than using dom selector.

Example : 

```
<quasar-tabs>
    <quasar-tab icon="home" :target="$els.tab1" active=true >Tab1</quasar-tab>
    <quasar-tab icon="list" :target="$els.tab2">Tab2</quasar-tab>
</quasar-tabs>

<!-- Targets -->
<div v-el:tab1>
  ...tab content 1...
</div>
<div v-el:tab2>
  ...tab content 2...
</div>
```

**Comment by rstoenescu** [comment]
Good idea. Will do. Thanks!

**Comment by rstoenescu** [comment]
Working on it.

**Comment by rstoenescu** [comment]
Seems like a problem because in certain scenarios `v-el` directive is evaluated after `:target="$els.tab1"` on a `<quasar-tab>`... Looking deeper to understand how Vue works under the covers.

**Comment by rstoenescu** [comment]
Pushed patch to enhance Tabs reactivity.

Unfortunately cannot implement target property taking HTMLElement due to Vuejs way of parsing v-el and dynamic component prop pointing to $els. The component property is evaluated before `v-el` and does not gets updated when `v-el` is available.

**Comment by mlenormand** [comment]
What is the best practice to refer to the HTMLElement tab contents in the quasar-tab "target" prop ?
1) Using raw id on each tab content element ? not optimal because of namespace collisions...
1) use CSS class namespace (one on root div on the component + one for each tab content element) ? also not optimal because of namespace collisions
3) maybe use some Vuejs-generated VM id ?

The fact that $els is not ready when using it in the props seems like a Vuejs bug, don't you think ?
I think $els and v-el has been introduced for these kind of use cases.

**Comment by rstoenescu** [comment]
Yep, it is a bug in Vuejs. Just didn't have time to report it :(

**Comment by rstoenescu** [comment]
Best practice at the moment would be to create unique HTML ids or class names and use them. Until VueJs bug is fixed. Then I'll make a patch for Quasar to support $els.
