### ISSUE TITLE
v-on:click events inside quasar-dropdown doesn't work

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#18]
When adding an event listener v-on:click on an element inside a quasar-dropdown, the event listener doesn't work. For example : 

`<span v-on:click="event1()" class="label">Test</span>
`

The problem comes from the folllowing code in dropdown-common.js, that close the dropdown on next mousedown event everywhere on the page.

`document.body.addEventListener('mousedown', this.close)`

**Comment by rstoenescu** [comment]
Reproduced. Will fix it.

**Comment by rstoenescu** [comment]
Progressing nicely.

Rewritten Dropdown (will be called Popover) and Context Menu.
The new Popover will also fix this bug.
Context menu will also work on mobile with a nice minimized Modal. Will delay commit for a few days to extensively test the changes as the code complexity is high and don't want to introduce bugs.
