### ISSUE TITLE
quasar-infinite-scroll continuously loads new items

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#23]
In quasar-infinite-scroll component, the handler method is called each time the user is scrolling, but it should scroll only when the user is at the bottom of the block. Currently, this behaviour make the page load new items several times per seconds.

Even in the infinite-scroll demo page, the loading is done when user scrolls to the 3th item, but we expect is to be done only when the user reach the end of the block/page.

**Comment by rstoenescu** [comment]
Infinite Scroll loads items in advance when less than one screen height is left to be seen. If the content you fetch has height less than the container's height on screen then Infinite Scroll will continue loading more content.

We can change that to start loading new content only when user hits the bottom of the container, but we lose the loading in advance, so user has to wait more for new content. What do you think the approach should be?

**Comment by smolinari** [comment]
> Infinite Scroll loads items in advance when less than one screen height is left to be seen. If the content you fetch has height less than the container's height on screen then Infinite Scroll will continue loading more content.

That sounds like the right was to do it to me. 

Scott

**Comment by rstoenescu** [comment]
This is the way it should work now already. Is the behavior different?

**Comment by mlenormand** [comment]
It's ok now, it was bad use of the component, sorry guys !

**Comment by rstoenescu** [comment]
Do you think the Inf Scroll documentation can be improved? Let's make it more clearer.

**Comment by mlenormand** [comment]
Maybe add to the docs what you explain in [this comment](https://github.com/rstoenescu/quasar-framework/issues/23#issuecomment-241353896).

**Comment by rstoenescu** [comment]
Done. Will publish v0.6.0 in a few hours with the updated doc website. Thanks for logging this bug!
