### ISSUE TITLE
The mobile demo view in Quasar documentation is truncated

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#24]
In Quasar documentation, the mobile demo view on the right of each page is truncated on my screen (1280 * 1024 px). I have to zoom out (90%) to reach the "View source" and "Desktop view" buttons.
This behaviour was not present a week or two ago when I discovered Quasar.

**Comment by rstoenescu** [comment]
Do you have a screenshot please? It looks fine for me.

Also, please open a bug for the doc website on https://github.com/rstoenescu/quasar-site repo only. Will keep this opened here today though.

**Comment by mlenormand** [comment]
![image](https://cloud.githubusercontent.com/assets/2403897/17849514/6da12d4c-6859-11e6-8ff8-2017e76ae8af.png)

Added this issue in quasar-site repo : https://github.com/rstoenescu/quasar-site/issues/3

**Comment by rstoenescu** [comment]
Closing issue here since opened on doc repo.
