### ISSUE TITLE
Date & time picker component

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#29]
Thanks for this amazing framework. I was surprised by the completeness of the components collection. One I do miss, is the datepicker component. Any plans to include it?

Some inspiration:
http://loujiayu.github.io/vue-material-design/#!/components/datepicker
https://github.com/hilongjw/vue-datepicker

**Comment by rstoenescu** [comment]
Thanks for the kind words. It will go in next release v0.7.0. I wanted to add it for a long time, and I think it's finally time to do it.

**Comment by musicformellons** [comment]
Marvellous. I am seriously impressed by your work and plan to use Quasar!

**Comment by rstoenescu** [comment]
Thank you and please go ahead and use it. Follow the Twitter account where all the Quasar news go and spread the word. The more we are the better Quasar gets.
Also, it's in no way required but take a look at the "Support Quasar" if you like.

**Comment by musicformellons** [comment]
For apple datepicker and calendar version you might find some inspiration here:
https://vux.li/

Currently this demo-site is down...; normally it is up.

**Comment by rstoenescu** [comment]
Great examples. Will work it for v0.7. Thanks for the tips!

**Comment by rstoenescu** [comment]
Working on it.

**Comment by smolinari** [comment]
Please also consider a date/time picker too. :smile: This one from Kendo isn't too shabby.

http://demos.telerik.com/kendo-ui/datetimepicker/index

Scott

**Comment by rstoenescu** [comment]
Yep. You'll be able to pick a date, a time or a datetime.

**Comment by rstoenescu** [comment]
Excited about the progress! It's gonna be a top-notch component.
