### ISSUE TITLE
Polished Lists

### ISSUE THREAD

**Issue by rstoenescu** [rstoenescu/quasar-framework#32]
Lists are probably one of the main elements when building a UI. Let's make them better!
List items should be called tiles.

* **1, 2 or 3 liners**
  * Tiles should be short and concise. If more details need to go into it, refer to the "expand/collapse" ability below.
* **One primary and one secondary (supplemental) action / icon / form component**
  ![components_lists_content2](https://cloud.githubusercontent.com/assets/4665641/17926308/1fca4e68-69f9-11e6-959d-aeaf62f0c301.png)
  * The primary element should be bigger in size than the secondary
  * Additional actions may be available if sliding (by swipe touch action) tiles to left or right. The additional actions will slide into view from left or right as if they are stick to the tiles.
  ![components_listcontrols_leave2](https://cloud.githubusercontent.com/assets/4665641/17925891/736cacf2-69f7-11e6-8e9c-7f75a3b392b1.png)
* **Ability to reorder tiles by dragging the secondary action.**
  ![components_listcontrols_reorder](https://cloud.githubusercontent.com/assets/4665641/17925849/45b38754-69f7-11e6-9120-030321b34946.png)
* **Ability to expand/collapse.**
  * It fits great for tiles and this way we can entirely remove the Collapsibles.
  * One great benefit that comes into mind is the Drawer which can use lists to create sub-menus
  ![components_listcontrols_expand1 1](https://cloud.githubusercontent.com/assets/4665641/17926113/5b3d4078-69f8-11e6-9630-5ea0a8a4edc4.png)
  ![components_listcontrols_expand2](https://cloud.githubusercontent.com/assets/4665641/17926135/7633030e-69f8-11e6-91cf-5b0368c79575.png)
* **Dividers as DOM elements**
  * Dividers should have their own DOM elements
  * Can be of two types: full-bleed (from left to right) and inset (starts on the left from beneath the tile content and goes to the right edge; so it skips the primary action)

Waiting for your comments!

**Comment by 37ch4** [comment]
I know this is closed but I would love to have the swipe actions and re-ordering mentioned in this proposal

**Comment by rstoenescu** [comment]
@37ch4 There's an opened ticket on swipe actions. It will get into Quasar 1.0.
But reordering? You're in control of the template where you use QLists, so the order is app-space specific.

**Comment by 37ch4** [comment]
Awesome thanks! Yeah I just loved the proposal you had for the draggable secondary action. As always amazing work!
