### ISSUE TITLE
Polished Search Component

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#37]
In the quasar-search component, the placeholder should be configurable.
Choosing the icon could be useful too (even if "search" icon is OK for majority of use cases).

**Comment by rstoenescu** [comment]
Make a detailed proposal please and we'll get this done in v0.7.0.

**Comment by mlenormand** [comment]
Prop "label-placeholder" for setting the placeholder to show
Prop "icon" for setting the icon name to be used

That's all, I don't see other improvements to make to this component. Maybe add autocomplete feature but I think this have to be thinked globally and implemented for all text input fields.

**Comment by rstoenescu** [comment]
Will add the two props to v0.7.0 and also think about autocomplete too, which was on my mind for some time too.

**Comment by rstoenescu** [comment]
Props "icon" and "placeholder" added.
