### ISSUE TITLE
Displaying Material Icons with longer names

### ISSUE THREAD

**Issue by ecerroni** [rstoenescu/quasar-framework#4]
When icons have names with multiple words, it almost never works on Cordova. Either they are not displayed at all or more than one icon is shown (wrong ones in any case)

Example. This one doesn't show up on Cordova:
<button class="primary clear small">
        <i>vertical_align_bottom</i>
      </button>

Example. This one show 2 icons (power and settings) on cordova disrupting the grid:

        <i>power_settings_new</i>

-------

Generally they work on desktop (Chrome and Firefox). I found the following not working with browsers though:

<i>star_rate</i>

Star icon is shown but Page Title is not aligned as the second word of the icon seems to take some space.

![star_rate](https://cloud.githubusercontent.com/assets/11174327/15959323/8b6b6d26-2efa-11e6-9422-21be72477f4b.png)

**Comment by rstoenescu** [comment]
Looking into it.

**Comment by rstoenescu** [comment]
One of the problems with Cordova wrapped Apps is that the runtime differes based on your phone/tablet.

Just released Quasar CLI v0.1.1 which also installs [Crosswalk plugin](https://crosswalk-project.org/documentation/about.html). This also adds the runtime to your App's package so it ensures your App is performing exactly the same on all phones/tablets.

First, `npm update -g quasar-cli`, then you have two options:

1. Delete the wrapper you've already made and create it again
   ``` bash
   $ rm -rf wrapper
   $ quasar wrap
   ````

2. Add the cordova-crosswalk plugin yourself:
   ``` bash
   $ quasar wrap plugin add cordova-plugin-crosswalk-webview
   ```

In either situations, uninstall your App from your phone/tablet then install it with the new wrapper (`quasar wrap run`). Run these steps and tell me if this solves your problem. I just tested with Samsung S4 and the icon issues seems to be fixed.

One problem remaining is that indeed "star_rating" icon is not displayed as it should. Further investigating.

**Comment by rstoenescu** [comment]
You can use `star` icon instead of `star_rate` until I figure out this issue.

**Comment by rstoenescu** [comment]
Ok, figured it out. It's a bug in the Material Design Icons woff font file.

Here is the link to it: https://github.com/google/material-design-icons/issues/302

Will keep this issue opened until a new version for Material Design Icons is released to fix this. Will then update quasar-framework to embed the new version.

**Comment by ecerroni** [comment]
Good to know. I'll try the new cli and let you know.

**Comment by ecerroni** [comment]
I installed and tried the new quasar-cli.

In order to make it work I needed to add "Android Support Repository" and "Google Repository" to my android sdk installation

Anyway it fixed the problem and also other few issues I didn't submit here on github.

All in all everything is working now as expected on Cordova. I also noticed a smoother behavior in animations and page transitions.

**Comment by rstoenescu** [comment]
Yes, you need the Android sdk installed and also to issue `quasar wrap platform add [platform]`. I should probably be more clear on the documentation. Will make a quick update now. Thanks for replying!

**Comment by rstoenescu** [comment]
Fixed in latest version of material-design-icons. Quasar v0.5 now lets use set your own dependency versions, so closing this as you can upgrade to mdicons' latest version.

**Comment by adoumas** [comment]
Still pending... I run same issue with CDN files. problem on star_rating but star and star_border are ok.
