### ISSUE TITLE
Vue 2.0

### ISSUE THREAD

**Issue by smolinari** [rstoenescu/quasar-framework#42]
I was wondering if Vue 2.0 conversion would be on the roadmap at some point?

Did I already ask this question? I just got a lot of deja vu and I went looking through the issues, but didn't find anything. :smile: 

Scott

**Comment by rstoenescu** [comment]
**Vue 2.0 is definitely on the roadmap.** Just not now. Waiting for the ecosystem to grow and become stable. I personally hate it when I stumble on packages that are not yet stable and find different bugs.

**Comment by smolinari** [comment]
Cool. And for sure, you should wait until Vue 2.0 is clearly stable. But, growing the ecosystem might even depend on Vue 2.0 being used. :smile: 

Scott

**Comment by rstoenescu** [comment]
Reopened issue so other know this thing is scheduled.

**Comment by smolinari** [comment]
FYI, The guys over at VueJS just released this migration guide.

**Comment by rstoenescu** [comment]
Saw that. Will see what I can do about it. I hardly wait to port everything to Vue 2.0 myself :)

**Comment by musicformellons** [comment]
@rstoenescu Probably hard to answer, but could you give an estimate when the Quasar Framework with vue 2.0 version will be there? As it could make me head for vue 2.0 at this time.

**Comment by rstoenescu** [comment]
I will probably start working on this one in one month top. Just to be sure, let's say it will be ready in 2 months. It all depends on how much money I can raise on Patreon so I can avoid working for others too to support day to day living :)

**Comment by rstoenescu** [comment]
Looked into Vue 2.0 and used the migration helper to see what needs to be changed. Will start working on this with first chance I get.

**Comment by rstoenescu** [comment]
Created `vue2` branch to handle this.

**Comment by rstoenescu** [comment]
Actively working on this on `v0.8` branch now

**Comment by laurentpayot** [comment]
Amazing work done. Moving to v0.8 right now ! :)

**Comment by rstoenescu** [comment]
Thx! Great!

**Comment by smolinari** [comment]
Yes. Appreciate hard and good work a lot. Vue is taking off like a rocket and that means frameworks like Quasar will be able ride the wave! 

Scott

**Comment by rstoenescu** [comment]
I sure hope so!
