### ISSUE TITLE
quasar website

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#43]
I am not sure whether to bother you with this or not, but it might be of help. I merely bringing this up since it kind of contrasts with the quality of docs, framework itself, etc. As a fan of the 'total quality' concept I feel like addressing it. I am on a 13 inch retina display and some parts of your website seem slightly less sharp. For sure this part:
![image](https://cloud.githubusercontent.com/assets/10334123/17959161/df609c14-6a9e-11e6-923c-7370df5befa9.png)

And maybe also the fonts in the toolbar, but maybe that's a color issue or something:
![image](https://cloud.githubusercontent.com/assets/10334123/17959203/1cb78064-6a9f-11e6-8c89-d7001e376183.png)

This part is sharp but messy due to small font and different size and not easy on the eyes colors:
![image](https://cloud.githubusercontent.com/assets/10334123/17959228/53b9b2bc-6a9f-11e6-8397-c7c74450ce80.png)

Now that I am at it, it is also a bit unclear why the top three are apart from the other features:
![image](https://cloud.githubusercontent.com/assets/10334123/17959313/df4a241a-6a9f-11e6-86ba-ed9903b4b24f.png)

If you really consider these three the 'top features' then maybe give them slightly more weight in font as well or something else, as now they just have different background which 'confuses me'.

To show differences in sharpness a picture of total page on my system:
![image](https://cloud.githubusercontent.com/assets/10334123/17959397/63e0501e-6aa0-11e6-892f-5f85ba9d9c7b.png)

**Comment by rstoenescu** [comment]
Thank you for this bug! You should open such a bug because it's important too.

Planning to rewrite the landing the page. Haven't given it much attention, so let's see if I can find time for the website too. One thing though, this should be opened against the website's github: https://github.com/rstoenescu/quasar-site

Open issues for anything. Quasar must be top notch on all aspects.

**Comment by musicformellons** [comment]
Ok! I opened it overthere.
