### ISSUE TITLE
alignment of breadcrumb arrows

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#44]
The alignment of breadcrumb arrows is slightly off:
![image](https://cloud.githubusercontent.com/assets/10334123/17961277/1398e39a-6aab-11e6-8677-654eecaa2cb7.png)

Also small white lines visible.

**Comment by rstoenescu** [comment]
What browser are you using?

**Comment by musicformellons** [comment]
Chrome Version 52.0.2743.116 (64-bit)

**Comment by rstoenescu** [comment]
Weird. It looks fine to me. Will investigate more.

**Comment by musicformellons** [comment]
Mmh, I am on Dell XPS 9343  13 inch with retina display; Ubuntu (gnome) 16.04

**Comment by rstoenescu** [comment]
Seems like I reproduced the small white lines issue by changing zoom through the browser. At least it's a starting point :)

**Comment by musicformellons** [comment]
Yeah, i checked as well. At zooms closer to 100% it improves. In Firefox same issue (seems slightly less off).
