### ISSUE TITLE
accordion; text realignment when opening

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#45]
For the default accordion and the Free - Can open multiple items simultaneously accordion the text realigns when opening.

**Comment by rstoenescu** [comment]
Accordions will be replaced by a feature for List tiles (former list items) in v0.7 soon, so not worth it to fix anything for Collapsibles.

The text realigning is an effect of changing the padding for the content. In my perspective I thought it was an interesting effect, but will drop it in v0.7. Anyway, thanks for addressing this!

Closing the bug and please wait for v0.7 aka "Polished" :)
