### ISSUE TITLE
Range demo

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#46]
In the last example the three ranges values seem slightly off from the one which was dragged last. Here the bottom one:

![image](https://cloud.githubusercontent.com/assets/10334123/17974299/d9f776ca-6ae5-11e6-9492-d90d3cc50c62.png)

Here e.g. the top one:
![image](https://cloud.githubusercontent.com/assets/10334123/17974330/f44a3d6e-6ae5-11e6-82ff-7f7cc6aba677.png)

**Comment by rstoenescu** [comment]
That's expected. If you want it to "snap" to values use `snap` attribute.
