### ISSUE TITLE
Window width related CSS classes doesn't work for some components

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#48]
Window width related CSS classes works by first setting "display:none" for all those classes and then display each of them depending of the window width (with media-query CSS). But some components have their own display CSS instructions that overrides the windows width related CSS classes.

**Possible fix, that works for me** : just move all window width related CSS classes at the end of the CSS file to take precedence over the components CSS instructions (may cause some side effects, not tested).

**Comment by rstoenescu** [comment]
some examples please?

**Comment by rstoenescu** [comment]
Please reopen with examples so I know what to fix :)
