### ISSUE TITLE
Quasar-tabs: how to dynamically change opened tab ?

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#50]
WIth quasar-tabs component, how can we set the active tab ?
This snipped doesn't work for me : 

```
<quasar-tab icon="menu" :active="selectedTab == 'main'" target="#tab-main">
Main menu
</quasar-tab>
<quasar-tab icon="search" :active="selectedTab == 'search'" target="#tab-search">
Search
</quasar-tab>
```

The search tab is shown the first time we set selectedTab to "search" value, but not the following ones.
And how to know which quasar-tab is currently shown ? Maybe by providing the quasar-tab component a 'selectedTab' prop that it has to automatically fill with the quasar-tab id/reference or something else.

My use case : programmatically change the selected tab by setting a component data.

**Comment by rstoenescu** [comment]
Would a `select()` method for `<quasar-tab>` help?

**Comment by rstoenescu** [comment]
Are you sure you're wrapping your `<quasar-tab>`s with a root `<quasar-tabs>`? If you don't, your code won't work. It you do, you'll know which tab is selected through `selectedTab` variable. Tested just now and it works. Please reopen if you still have an issue.

**Comment by mlenormand** [comment]
Sorry, my description wasn't precise enough : I want to know which is the current selected tab, and not the "active by default" tab. And I couldn't find a way to programmatically set the current selected tab. I was thinking about adding a "selectedTab" variable that would be updated automatically by the quasar-tabs component, and that implies to give an "id" for each quasar-tab component.

**Comment by rstoenescu** [comment]
Will add "selectedTab" with a ref to current selected tab.

**Comment by rstoenescu** [comment]
Example of dynamically changing tabs:

``` html
    <quasar-tabs>
        <quasar-tab icon="assignment_returned" :active="view === 'templates'">
          Templates
        </quasar-tab>
        <quasar-tab icon="person" :active="view === 'men'">
          Men
        </quasar-tab>
        <quasar-tab icon="person_outline" :active="view === 'women'>
          Women
        </quasar-tab>
      </quasar-tabs>
```

Works with v0.7. Will make an enhancement for v0.8 and v0.9.

**Comment by calmed** [comment]
How to set a default tab open on page load ?

**Comment by nothingismagick** [comment]
This is not a code issue. Please visit the forum or the discord chat
server.
