### ISSUE TITLE
Dialog prompt component is covered by input widget

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#51]
Don't know whether there is a good solution for this, but for instance in this case have it already scroll down would be an improvement I suppose.

See:
![screenshot_20160826-111411](https://cloud.githubusercontent.com/assets/10334123/18000577/0e02e0a0-6b7f-11e6-9d02-65b6893fc1ad.png)

**Comment by rstoenescu** [comment]
Don't think this will be an improvement as the title and description would be skipped. User has to read them first before filling in input boxes. Reopen if you have an idea on how user can read title and description while input textbox being focused.
