### ISSUE TITLE
Quasar-select are not useable in drawers

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#53]
I'm using a quasar-select component in the left drawer. There is some issues with that : 

![image](https://cloud.githubusercontent.com/assets/2403897/18001034/4b5ccda6-6b81-11e6-9c90-440dd0301285.png)

- The select window is not opened on the center of the screen
- The drawer is not "backdropped" as the other parts of the screen

I consider drawers as normal places for displaying content, forms, etc. and not just UI menus (in my case I found interesting to show search forms in the drawer to allow quick access to it with small view and permanent access in larger views.
In fact, all my app views can display some additional content in the second tab of the drawer, and the first tab is the same for all the layout views (mainly used for the main app menu). In think this philosophy allows rich UI for all kind of screens in a variety of use cases. What do you thing about that ?

**Comment by rstoenescu** [comment]
Hmm, nice. Didn't think of this case. You better use a Popover with a list with the three radios here. But anyway, investigating if this bug can be done, otherwise documenting that you shouldn't use it. The code there is quite complex and I don't want to make it even more complex.

**Comment by rstoenescu** [comment]
Will make it work.
