### ISSUE TITLE
Polished Infinite Scroll

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#54]
I have a search result list wrapped by a quasar-infinite-scroll.
When a new search is triggered, I empty the 'items' array to and reset the quasar-infinite-scroll 'index' value to 0. After that, I expect the infinite-scroll to call loadMore() function in order to load and show new items but it's not the case. Or perhaps I'm not doing it the right way ?
Maybe it would be interesting to add a "reset" method to the component, or make it automatically handle this situation ?

**Comment by rstoenescu** [comment]
Basically you can set index to 0 and call the handler (`loadMore()` in your case) yourself. Will add a reset() method to do that for convenience. But the content must be reset by you since it's controlled by variables in your page's scope (`items` in your case).

So adding reset() which sets index to 0 and calls handler. Is this what you expect? Please confirm.

**Comment by mlenormand** [comment]
Yes, I ended up setting the index value to 0 and calling the handler myself. But it's not ideal because we have to provide the handle function with an index value and a callback function that set refreshing to false (forced us to know the implementation details of the component).

```
resetList() {
  this.$refs.infiniteScroll.index = 0;
  var me = this;
  this.loadMore(this.$refs.infiniteScroll.index, function() {
	me.$refs.infiniteScroll.refreshing = false;
  });
}
```

**Comment by rstoenescu** [comment]
Infinite Scroll component now has two more methods:
  * reset ([Boolean])
      * resets index and loads more content
      * if parameter is "true" it does not load more content
  * loadMore ()
      * triggers a "refresh" calling your "handler"

**Comment by mlenormand** [comment]
Perfect !

There is a small problem when I manually reset the component (with my own code, not tested with your methods yet). Only a first load is done, and user have to scroll to load the following items. But maybe it's resolved by the fix you've just added.

![image](https://cloud.githubusercontent.com/assets/2403897/18012420/a3d87ee8-6bb9-11e6-8a05-d06bede2d2e4.png)

I tried to manullay call the "scroll()" method in my custom reset method, but I have the following error : 

`Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.(…)`

**Comment by rstoenescu** [comment]
Yep, it's fixed in my commit. v0.7 will have it, which will be released really soon.

**Comment by hassam-saeed** [comment]
@rstoenescu  I am facing the same issue. Is this resolved?
I am not able to find the method loadMore
