### ISSUE TITLE
quasar checkbox may not work on iphone

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#55]
With the Chrome mobile view (devtools), with Iphone 4/5/6/Ipad, checkbox doesn't work.
Well, in fact it works only when clicking the label, not when clicking the checkbox itself.
And with the "inside of a list" demo or the "checkbox label" demo, it doesn't work at all, neither when clicking the label or clicking the checkbox.

Don't have an iPhone to confirm the bug on a real device.

![image](https://cloud.githubusercontent.com/assets/2403897/18013106/efd8890c-6bbc-11e6-82d4-ff76ae8e887d.png)

**Comment by rstoenescu** [comment]
Remember dev tools is just an "emulator" and works far from perfect! I get this issue too sometimes but closing all chrome tabs and then reopening usually makes it work again.

**Comment by rstoenescu** [comment]
Plus not to mention, the "iPhones" from chrome dev tools just offer the size of an iphone and the correct agent string in request headers.

**Comment by ahmedkassem** [comment]
I tried on actual iphone and I have same problem
you cant select from checkboxes
you have to try so many times to check a box

**Comment by rstoenescu** [comment]
What iPhone do you have?

**Comment by ahmedkassem** [comment]
I tried it on iPhone 5S and iPhone 6

**Comment by rstoenescu** [comment]
Are you sure you're not wrapping checkboxes with multiple `<label>`s?

**Comment by ahmedkassem** [comment]
only one

**Comment by rstoenescu** [comment]
Temporarily remove that one too until I figure this out. Damn browser implementation :)

**Comment by ahmedkassem** [comment]
ok thanks a lot
