### ISSUE TITLE
Minor UX enhancement for tabs component

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#58]
Very minor issue but total quality concept implies correct all issues, even the minor ones, right :-) ?

It's not really a bug but I found it not optimal/useable to show the arrow when there is not other tabs to show.
For example, in the following case, clicking the arrow make the tabs area move to the left just a little bit

Before clicking the arrow : 

![image](https://cloud.githubusercontent.com/assets/2403897/18018452/47866ea2-6bd7-11e6-9aca-99d9d8638fd8.png)

After clicking the arrow : 

![image](https://cloud.githubusercontent.com/assets/2403897/18018481/813b3ace-6bd7-11e6-908f-eedf12e1d5fb.png)

**Comment by rstoenescu** [comment]
You're right, but not really worth spending time on it at the moment. Maybe in the future. Or if you feel like it you can clone the repo and give it a try. Thanks for logging this!
