### ISSUE TITLE
New component: Select without Modal

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#59]
I know there is the Select component that allow to choose an item in a list, but we it's quite "heavy", a popup show up, and the user have to click "ok" or cancel. I think a more lighweight component just like [this one](http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu) would be better for the majority of use cases.

**Comment by rstoenescu** [comment]
There is such a component: Popover. You just have to populate it with the right content.

**Comment by rstoenescu** [comment]
I'll write some types of Popovers for convenience. Thanks for pointing this out!

**Comment by mlenormand** [comment]
I was thinking more of a specific component to cover the frequent use case of a "select" box that shows the value selected from a list (basically the HTML select element). To implement this with the Popover component, we have to handle the click event on a list item, fill the label with the label associated with this list item. But I agree the Popover solution to handle this is more flexible, we can format items as we want, choose the right label, etc.

**Comment by rstoenescu** [comment]
* `<quasar-dialog-select>` opens a Dialog
* `<quasar-select>` opens up a Popover; three types available: `radio`, `checkbox`, `toggle`
