### ISSUE TITLE
AJAX Post data casted to string

### ISSUE THREAD

**Issue by kamilersz** [rstoenescu/quasar-framework#6]
I tried to send POST data to server using this code

`        var thisVm = this;

        quasar.make.a.post.request({
          url: 'message/new',
          data: {
            title: thisVm.title,
            content: thisVm.content,
          },
          xhrFields: {
            withCredentials: false
          }
        })
        .done(function(jsonObject) {
          quasar.navigate.to.route('#/');
        })
        .fail(function(jqXHR, textStatus, errorThrown) {
          console.log('uh, oh... the request failed...', errorThrown);
        });
`

but the form data sent as string

![erro](https://cloud.githubusercontent.com/assets/2652633/15984551/ccf98d22-2ff9-11e6-89a7-8fbd33769207.jpg)

**Comment by kamilersz** [comment]
If the data set as string, then the form data is sent correctly
`
data: 'title=' + thisVm.title + '&content=' + thisVm.content
`

**Comment by rstoenescu** [comment]
When using an Object or Array as data for your POST request then the data is JSON stringified hence the "string" representation. If on the other hand your data is already a string, it will be sent as-is.

Will update the documentation website to include this.
