### ISSUE TITLE
Tabs Styling

### ISSUE THREAD

**Issue by ahmedkassem** [rstoenescu/quasar-framework#61]
When using tabs, the tabs are stacked besides each other leaving a lot of space at the right and the left side, even when applying justify-around

**Comment by rstoenescu** [comment]
Hi, can you be more specific please? Take a screenshot and highlight your areas of interest then drag-n-drop it here. Thanks!

**Comment by ahmedkassem** [comment]
![111](https://cloud.githubusercontent.com/assets/7607004/18022490/9cebccd0-6bef-11e6-9b89-712e1c936783.png)

**Comment by rstoenescu** [comment]
Can you also copy paste your layout's template pls? I want to check something. Thanks!

**Comment by ahmedkassem** [comment]
`    <quasar-tabs class="justify-around primary inverted">
  <quasar-tab icon="mail" target="#tab-1">
    Tab 1
  </quasar-tab>
  <quasar-tab icon="alarm" target="#tab-2">
    Tab 2
  </quasar-tab>
  <quasar-tab icon="alarm" target="#tab-2">
    Tab 2
  </quasar-tab>
</quasar-tabs>`

**Comment by rstoenescu** [comment]
I was interested more in how and where you place the tabs within the template. But nevertheless, Tabs are CSS responsive. On wide enough windows they stack to the left while on narrow windows they occupy all available width while dividing equal space for each tab. Most if not all Quasar components are designed to have width 100% (and not some predefined fixed width) so that you can wrap them in a `div` or other node type which actually has the width that you want. I won't get into details, but it works great with layouts or "layout-padding".

It's very late here and I'm exhausted and I'll continue tomorrow to help you, but what I suggest is that you wrap those Tabs in a DIV or even better in a Toolbar and set the width there. Your tabs will stack to the left and hopefully if I understood correctly this is what you want. Or try setting the width directly on `<quasar-tabs>`. Talk to you tomorrow more.

**Comment by rstoenescu** [comment]
And make sure you don't have alignment set to center on your page's content. If so, explicitly set it to left (or right) on `quasar-tabs`.

**Comment by ahmedkassem** [comment]
`<template>
  <div>
    <div class="layout-padding">
    <quasar-tabs class="justify-around primary inverted">
  <quasar-tab icon="mail" target="#tab-1">
    Tab 1
  </quasar-tab>
  <quasar-tab icon="alarm" target="#tab-2">
    Tab 2
  </quasar-tab>
  <quasar-tab icon="alarm" target="#tab-2">
    Tab 2
  </quasar-tab>
</quasar-tabs>
      <h5>List with Avatars</h5>
      <div class="list inner-delimiter">
        <div class="item">
          <img class="avatar" :src="'statics/linux-avatar.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">Jack</p>
              <p>Linux Lover</p>
            </div>
          </div>
        </div>
        <div class="list-header">Header</div>
        <div class="item">
          <img class="avatar" :src="'statics/guy-avatar.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">John</p>
              <p>Web Developer</p>
              <p>Quasar Framework enthusiast</p>
            </div>
            <i>supervisor_account</i>
          </div>
        </div>
        <div class="item">
          <img class="avatar" :src="'statics/boy-avatar.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">Joe</p>
              <p>Newbie</p>
            </div>
            <i>supervisor_account</i>
          </div>
        </div>
        <div class="item">
          <img class="avatar" :src="'statics/linux-avatar-2.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">Linux Lover</p>
              <p>Linux rulz!</p>
              <p>Quasar rulz!</p>
            </div>
            <i>supervisor_account</i>
          </div>
        </div>
      </div>

      <h5>List with Thumbnails</h5>
      <div class="list inner-delimiter">
        <div class="item">
          <img class="thumbnail" :src="'statics/linux-avatar.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">Jack</p>
              <p>Linux Lover</p>
            </div>
          </div>
        </div>
        <div class="list-header">Header</div>
        <div class="item">
          <img class="thumbnail" :src="'statics/guy-avatar.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">John</p>
              <p>Web Developer</p>
              <p>Quasar Framework enthusiast</p>
            </div>
            <i>supervisor_account</i>
          </div>
        </div>
        <div class="item">
          <img class="thumbnail" :src="'statics/boy-avatar.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">Joe</p>
              <p>Newbie</p>
            </div>
            <i>supervisor_account</i>
          </div>
        </div>
        <div class="item">
          <img class="thumbnail" :src="'statics/linux-avatar-2.png'">
          <div class="item-content">
            <div class="item-label">
              <p class="item-title">Linux Lover</p>
              <p>Linux rulz!</p>
              <p>Quasar rulz!</p>
            </div>
            <i>supervisor_account</i>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>`

**Comment by ahmedkassem** [comment]
I only have the chat component and the tabs component in this file and they are shown within the layout-play.vue file as provided in your demo app

**Comment by rstoenescu** [comment]
Remove the `justify-around` CSS class from `<quasar-tabs>`.
