### ISSUE TITLE
Parallax, movement of background pictures

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#62]
Thanks for implementing the 'moving' parallax:
https://github.com/rstoenescu/quasar-framework/issues/49

Cool!

Small thing though, I noticed the first picture moving down, whereas other move -as expected- upwards.

**Comment by rstoenescu** [comment]
Where are you looking for this?

**Comment by musicformellons** [comment]
I downloaded current github dev version...

**Comment by rstoenescu** [comment]
Hmm, I hope we don't bump into same long discussion as yesterday :), but I see all moving same... And anyways, they all share exactly same code logic... Help?

**Comment by rstoenescu** [comment]
It may be an illusion since first pic is smaller...

**Comment by rstoenescu** [comment]
Yep, that's it. Just an illusion. Parallax is trying to show as much as the image as it can during a full scroll, so it makes it have a "higher speed" for a smaller container than for a small Parallax container.

**Comment by musicformellons** [comment]
It is not an illusion. When in full screen the background picture is not moving at all. When I make the screen mobile size it moves down instead of up while scrolling.

**Comment by musicformellons** [comment]
Hope this works and gives an impression:
![gifrecord_2016-08-27_171130](https://cloud.githubusercontent.com/assets/10334123/18028239/ae9d2502-6c79-11e6-8145-59eba271ee4e.gif)

**Comment by musicformellons** [comment]
I thought I noticed some issue fatigue on your side, so I felt it was the right time to pull my wallet via bountysource. Keep up the good work! Looks great already!

**Comment by rstoenescu** [comment]
Thank you so much for your generous donation!!! Every cent counts.

**Comment by rstoenescu** [comment]
Wish there were more like you!

**Comment by musicformellons** [comment]
No worries, they will come.
