### ISSUE TITLE
Modal Example Problem

### ISSUE THREAD

**Issue by ahmedkassem** [rstoenescu/quasar-framework#63]
I want to have only one button to show one Modal like the one in the Components Page in the website

https://github.com/rstoenescu/quasar-play/blob/master/src/components/showcase/global/modal.vue

and here is the code, but still doesnt work (N.B I kept all the script code same as in the modal.vue)

`<template>
  <div>
    <div class="layout-padding">

      <div class="list item-delimiter highlight">
        <div
          class="item cursor-pointer"
          @click="openBasicModal()"
        >
          <i class="text-primary">open_in_new</i>
          <div class="item-content">
            <div class="item-label">Basic Modal</div>
            <i>keyboard_arrow_right</i>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>`

**Comment by rstoenescu** [comment]
So basically what you are saying is that openBasicModal() does not trigger?

openBasicModal() below:
``` js
Modal.create({
    template: '<p v-for="n in 10">This is a basic modal. Scroll down to close.</p><button class="secondary" @click="close()">Close Me</button>'
  })
  .css({
    padding: '50px',
    minWidth: '50vw'
  })
  .show()
```

**Comment by ahmedkassem** [comment]
yep, but when I copy everything in the https://github.com/rstoenescu/quasar-play/blob/master/src/components/showcase/global/modal.vue it works fine and I want only an example for only one button to show one Modal and dont know how to do it

**Comment by rstoenescu** [comment]
Then this would be the correct code for your `*.vue` file:

```
<template>
  <div class="list item-delimiter highlight">
    <div
      class="item cursor-pointer"
      @click="openBasicModal()"
    >
      <i class="text-primary">open_in_new</i>
      <div class="item-content">
        <div class="item-label">Basic Modal</div>
        <i>keyboard_arrow_right</i>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  methods: {
    openBasicModal () {
      Modal.create({
        template: '<p v-for="n in 10">This is a basic modal. Scroll down to close.</p><button class="secondary" @click="close()">Close Me</button>'
      })
      .css({
        padding: '50px',
        minWidth: '50vw'
      })
      .show()
    }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Or the template can contain:

``` html
<template>
  <button class="primary" @click="openBasicModal">Open Modal</button>
</template>
```
