### ISSUE TITLE
Inifinite-scroll : handle the case when the list has finished loading items

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#64]
There is currently no way to tell the infinite-scroller that the list is completed and no additional items will be loaded. We can handle ourself this feature with a stopLoading variable in our component, but it's not ideal and I think it would be better to add it to the component directly.

**Proposal** : pass a stopLoading parameter with the done() callback. If stopLoading is true, infinite-scroll will not try to load more items. Reinit stopLoading to false in the reset function. Generraly, the stopLoading value will be calculated from the pagination elements in the AJAX response call (if nb of items already loaded >= nb of total items).

**Comment by rstoenescu** [comment]
Good point. Let me make up a detailed design to discuss more and will push a commit afterwards.

**Comment by rstoenescu** [comment]
Infinite Scroll methods:
* loadMore() --> calls handler (index, function (stopLoading) {...} )
* reset() --> resets index and starts it again, but DOES not trigger a loadMore()
* stop() --> stops loading more
* resume() --> starts it AND calls loadMore()

Infinite Scroll props:
* handler
* inline --> when using inside an overflowed container
* offset --> Number representing offset in pixels of content height left to read that should trigger a loadMore()
* stopped --> Boolean which specifies Infinite Scroll state (working or stopped)

Comments?

**Comment by mlenormand** [comment]
Perfect !

**Comment by rstoenescu** [comment]
Will get into v0.7
