### ISSUE TITLE
Programmatically open/close the drawer

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#69]
Programmatically open/close the drawer .

Here is my use case : my search button goes to the /search page where the search form is inside the left drawer. I need a way to open/close the drawer when the /search page is opened.

**Comment by rstoenescu** [comment]
Will add a "close()" and "open()" method for convenience. You can use it now by calling "setState(Boolean open/close, function done)".

**Comment by mlenormand** [comment]
Currently, there is the the following behaviour on a large screen where the drawer is already showed : a blank area is showed when we set setState(true).

![image](https://cloud.githubusercontent.com/assets/2403897/18167756/a1c3c0d4-7052-11e6-9b19-4a11da2b08ea.png)

It's OK on a small screen where the drawer is hidden at first.
