### ISSUE TITLE
infinite-scroll call the handler function when we're not ready yet to load items

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#71]
With the infinite-scroll component, the handler function is called immediatly after the component is ready.
But what if we are not ready to load new items ? For example, in my use case, I'm waiting for an asynchronous call to complete before loading new items. Moreover, how can we control the "index" data of the components ? What if we want to "refuse" loading new elements in the handler function (i.e asking the infinite-scroll not to increment the index function ?).

I know I'm posting a lot of issues these days, but it's because I'm using intensively Quasar and I meet some deep issues/problems ;-)

**Comment by rstoenescu** [comment]
Don't worry, log them out.

This is already fixed (in future v0.7) by adding the "working" property. Set it to false on start and change whenever you need loading content. As for the index you can tamper with it directly from Inf Scroll v-ref.
