### ISSUE TITLE
error: cb() never called!

### ISSUE THREAD

**Issue by nerijunior** [rstoenescu/quasar-framework#80]
When I tried to install the `quasar-cli` everything is ok but when I tried to init a project I got:

```bash
 $ ~/apps  quasar init teste

 ℹ Generating Quasar App...

 ✔ Latest App template is v1
 ✔ Downloaded App template v1
 ✔ Generated Quasar App from template "v1" in /Users/nerijunior/apps/teste

  To get started:

  $ cd /Users/nerijunior/apps/teste
  # edit package.json
  $ npm install
  $ quasar dev

$  ~/apps  cd teste
$~/apps/teste  npm i
npm ERR! cb() never called!
```

**Comment by rstoenescu** [comment]
That is an NPM error. Nothing to do with Quasar. What NPm and Node are you using and what's your platform (win, linux, mac)? Please refer to NPM for this error.

**Comment by nerijunior** [comment]
@rstoenescu Thanks by the fast reply, I searched by this error message but without succes:

I'm using Mac El Capital 10.11.6
node v5.9.1
npm 3.10.6

**Comment by nerijunior** [comment]
```bash
nvm install v6.5.0
nvm use 6.5.0
npm install -g npm@latest
```

Now everything is ok!

**Comment by rstoenescu** [comment]
Great! Have fun with Quasar now :)
