### ISSUE TITLE
how to use quasar-cli with more current version

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#86]
When using quasar-cli and 'quasar init' as described in the docs I get quasar-framework 2.0, so that is way behind the 6.0 master version. When installing like that the quasar-framework is installed in the node_modules folder and then 'required' into the actual project. 

However when I install the more current 6.0 version I simply download the github master version and install it with 'npm install' and then the framework is not in the node_modules folder but 'in my actual project'. Is this a change of project structure as the structure changed between versions 2.0 and 6.0, or is it because I am not using 'quasar init'?

**Comment by rstoenescu** [comment]
1. You mean v0.2 and v0.6
2. Are you trying to update Quasar version for one of your projects? A simple "npm update quasar-framework" will suffice. The "quasar-framework" dependency is marked as "0.x" which means it will upgrade to ANY new version up to v1.0.
3. If for some reason you are running with an older NPM, simply edit `package.json` on a newly created `quasar init` folder and replace `quasar-framework: 0.x` with `quasar-framework: ^0.6.0`. Note that this change will not trigger an update to v0.7 when it will be available and so you have to manually edit the file again and npm update it.

Please reopen if I am missing something.

**Comment by musicformellons** [comment]
Thanks for the clear answer. One more thing: So the Quasar Framework is supposed to be in the node_modules folder, right? (as it was in the 0.2 version and after updating to 0.6 it will still be there).

**Comment by rstoenescu** [comment]
That's correct. It should always be in node_modules, installed by NPM.
