### ISSUE TITLE
HMR with vuefire

### ISSUE THREAD

**Issue by beebase** [rstoenescu/quasar-framework#87]
Has someone already tried quasar dev with vuefire? All works well, except that Hot module replacement seems to wipe out data after a firebase call.

**Comment by beebase** [comment]
Maybe this question should be posted @github/vuefire

to be more clear:
this won't work with HMR
![img2262](https://cloud.githubusercontent.com/assets/446089/18417310/23f7f602-782c-11e6-9069-e347117eda1b.jpg)
this will work
![img2261](https://cloud.githubusercontent.com/assets/446089/18417309/23f7f382-782c-11e6-831e-c78aec379279.jpg)

**Comment by rstoenescu** [comment]
Haven't worked with vuefire yet, but I thinks it needs special treatment from HMR. Currently only "data" is persistent. I see that "firebase" property there which surely gets reinitialized. Will try to make HMR work with it first chance I get, but it may take quite a while. Thanks for reporting!

**Comment by rstoenescu** [comment]
Please open up an issue on https://github.com/vuejs/vue-hot-reload-api repo for this one.

**Comment by foufrix** [comment]
@beebase Hello, i have question regarding general firebase configuration in quasar, can you send a screeshot of your firebase-connect.js ? 

Thank you in advance !
