### ISSUE TITLE
can run server

### ISSUE THREAD

**Issue by twappleon** [rstoenescu/quasar-framework#88]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! quasar-app@0.0.1 build: `node build/script.build.js`
npm ERR! Exit status 1

**Comment by rstoenescu** [comment]
Seems to be an issue strictly with NPM. Please update to NPM v3.
``` bash
npm update npm
```

**Comment by rstoenescu** [comment]
It's anyway recommended to use NPM v3 due to its superior dependency tree handling. Thanks for reporting though!
