### ISSUE TITLE
How to preview ios and android version of the app in browser?

### ISSUE THREAD

**Issue by IniZio** [rstoenescu/quasar-framework#9]
Is there a way to display the appearance of the app on both platforms in browser?

**Comment by rstoenescu** [comment]
If you mean simultaneously, side by side, this is currently not available, but will be in the future.

Meanwhile you can switch between the two themes easily by calling `quasar.swap.theme()`. Either call it in the browser console or make a temporary button in your layout or page for this:

``` html
<button class="primary" @click="$quasar.swap.theme()">Swap</button>
```

Make sure you are building both themes in your `quasar.build.yml` file by commenting out (or removing) the `forceTheme` property. Please note that live previewing with both themes is a little more costly than building just one.

Please also note that Quasar detects that you are running under a desktop browser and there are some subtle differences for mobile platforms. To emulate an iOS or Android device, use Google Chrome: open Developer Tools (Ctrl+Shift+J) and click on Toggle device mode (Ctrl+Shift+M). Select iPhone 5 or Galaxy S5 then refresh your browser so Quasar picks up the new platform.

![screenshot from 2016-06-29 13 58 50](https://cloud.githubusercontent.com/assets/4665641/16449806/29c2ae60-3e02-11e6-8d4b-c385b76e7073.png)

> Will add support to preview both themes side by side in the future.

**Comment by IniZio** [comment]
Thank you!

**Comment by denisx304** [comment]
Hello @rstoenescu .

I'm currently using quasar as a node module, as follows:
`npm install quasar-framework`
Then, 
`import Vue from 'vue'
import Quasar from "quasar-framework/dist/quasar.mat.esm";
import "quasar-framework/dist/umd/quasar.mat.css";
Vue.use(Quasar);`

In my Vue instances I'm getting a reference to quasar by `$q`, but there is nothing available such as `$q.swap.theme()`.

How can I get this feature working?

**Comment by rstoenescu** [comment]
@denisx304 There is no way to swap themes currently, due to how Webpack works.
