### ISSUE TITLE
Fantastic release!!!

### ISSUE THREAD

**Issue by smolinari** [rstoenescu/quasar-framework#90]
Hi Razvan,

I just wanted to say thank you for the great work you are doing on Quasar. The 0.7.0 release has a lot of new stuff that makes me drool (the datetime chooser is awesome!!!) and want to use Quasar for our project even more. I can't wait to get started (which is still a few months off). 

Thanks again and keep up the great work! I am certain we'll be doing business together in the future. :smile: 

Scott

**Comment by rstoenescu** [comment]
Thanks for all the appreciations! I wouldn't normally do this, but take a look at http://quasar-framework.org/support-quasar-framework.html . I need some help so I can keep full-time focus on Quasar. Spread the word!

**Comment by smolinari** [comment]
I'm also tight on budget currently, but if something I plan to let happen (not in the tech world) goes viral, I will certainly be able to help, possibly. Depends on what ends up happening. Cross your fingers. 

I've already done some tweeting for you and Quasar too. 😄 

Scott
