### ISSUE TITLE
any breaking changes from 0.6 to 0.7 ?

### ISSUE THREAD

**Issue by beebase** [rstoenescu/quasar-framework#91]
Are there any breaking changes or syntax changes coming from 0.6 to 0.7.0 ?
List views seem to be affected.
![img2272](https://cloud.githubusercontent.com/assets/446089/18631548/e2b6bc76-7e72-11e6-994d-2070ae118a0c.jpg)

**Comment by rstoenescu** [comment]
Yes, there are some needed breaking changes. Read the release notes (always).
https://github.com/rstoenescu/quasar-framework/releases/tag/v0.7.0

**Comment by beebase** [comment]
Thanks, I couldn't find the release notes , but I know now where to look for future releases.
Love this framework!
