### ISSUE TITLE
quasar build process doesn't end

### ISSUE THREAD

**Issue by beebase** [rstoenescu/quasar-framework#92]
I wonder what the average build time should be with a clean quasar install? Mine takes about a minute, but as I start adding components, the build time seems to increase exponentially. After adding about 10-20 files , the build time is ~3min.  At 20-30 files the build doesn't finish anymore (I killed it after 30 min) The node process is also on 100% cpu load non stop, with memory consumption around 500Mb

OSX 10.11.6
node 3.10.5
quasar 0.7.0

**Comment by rstoenescu** [comment]
Hmm, are you sure you don't have any circular references? I'm sure Quasar Play has more than 30 files. The build takes a few minutes, yeah, but this is due to the maaany many optimizations that need to be executed. Anyway, have never encountered a build not to finish. My guess is that you have a circular reference. Can you investigate a little, please?

**Comment by beebase** [comment]
I also suspect it must be related to my code somewhere. Can't imagine that such an issue would have stayed unnoticed. Will report back here, what is causing the stall.
Thanks.

**Comment by beebase** [comment]
I'm beginning to think there's a bug somewhere in webpack. If my code would have circular references, then that would certainly show up running quasar dev.
Is there a setting in webpack to activate any logging during quasar build?
Searching on google, I've seen issues where webpack slilently fails.

**Comment by rstoenescu** [comment]
In these kind of situations I recommend taking one file at a time and determining where the problem is. For example, I found a bug in vue-rollup where it silently fails if a .vue file does not have a `<script>` tag, whereas vue-loader does not require it. Took me lots of time to find this out by taking one file at a time and some intuition :)
What you are experiencing may be an error in webpack, vue-loader, css-loader or any other loaders... Take this approach and see where things change. A divide et impera startegy might also be good to win some more time.
It will be an interesting one this issue.

**Comment by rstoenescu** [comment]
Taking one file at a time ---- meaning removing one file at a time from the build.

**Comment by beebase** [comment]
Ok, I managed to strip down the file to bare minimums and discovered that this criples quasar build
![img2286](https://cloud.githubusercontent.com/assets/446089/18729655/e864efc6-8052-11e6-8d92-ecc989902253.jpg)
and this doesn't
![img2287](https://cloud.githubusercontent.com/assets/446089/18729684/0048911a-8053-11e6-90c1-87fab409ff78.jpg)

So it does have something to do with the router file.
I will test again tomorrow with a clean quasar install and see what happens then.
(maybe my own router.js has buggy code)

**Comment by beebase** [comment]
After doing  a lot of builds there doesn't seem to be going anything wrong. Except that at some point the build time grows exponentially.  By doing addFile-build-addFile-build etc.. I went from 3 to 5 etc.. to 12 min and then adding one file again, suddenly to 2,5 hours.

I'm going to test again from scratch. But this time only just using empty template files. See what happens then. (in my own project I'm adding npm install firebase, who knows...)

btw: Is there any possibility you could add some logging into the build phase? Maybe a timestamp/duration for each task that webpack performs? Doesn't necessarily have to be realtime. A log file afterwards will also do. If you know of any modules/documentation that achieve this in webpack, I'll be happy to try and add them myself during tests. Really want to nail this cause I want to start beta testing a quasar app with users in 1 or 2 months.

**Comment by rstoenescu** [comment]
Will see what I can do. That debugging would be quite useful, yes.

**Comment by rstoenescu** [comment]
From the Webpack doc website. There's a `debug` option you could use which switches loaders to debug mode. Add `debug: true` to top level of exported object in `build/webpack.base.config.js` and see what happens. Don't forget to remove it after your investigation :)

**Comment by beebase** [comment]
Will try!

**Comment by rstoenescu** [comment]
Any progress? Just curious.

**Comment by beebase** [comment]
Ran in debug mode last week. After adding more pages/code, the build takes like 8 hours now, but no error outputs. I still have no idea what could be the cause. Right now I'm focussing on coding in dev environment to get my project ahead. (which is going very smooth with quasar and firebase.) Basically skipping entire app server coding :-) 
I think I'll build a small side project this weekend based on todomvc (which I can share). See if that build goes faster.

**Comment by rstoenescu** [comment]
Can you try with node 4 and latest npm? Also, did the debug method produce any results?

**Comment by rstoenescu** [comment]
Let's move this issue to https://github.com/rstoenescu/quasar-templates/issues
Trying to organize things here :)

**Comment by ricar2ce** [comment]
> From the Webpack doc website. There's a `debug` option you could use which switches loaders to debug mode. Add `debug: true` to top level of exported object in `build/webpack.base.config.js` and see what happens. Don't forget to remove it after your investigation :)

i need something like that for vite, can you give some help please?, my proyect take 3 hours for build
