### ISSUE TITLE
Form Input Validation

### ISSUE THREAD

**Issue by rstoenescu** [rstoenescu/quasar-framework#96]
Is there any good vue validation out there or should Quasar have its own?

**Comment by smolinari** [comment]
Not sure how good or bad it is, but there is this. https://github.com/vuejs/vue-validator

Scott

**Comment by musicformellons** [comment]
Not worked with it but this one is currently at top of my list:
http://vee-validate.logaretm.com/

**Comment by XristMisyris** [comment]
+1 for vee-validate

**Comment by rstoenescu** [comment]
I like `vee-validate` too. Did anyone used it with Quasar?

**Comment by smolinari** [comment]
Yes, vee-validate looks pretty good.

Scott

**Comment by rstoenescu** [comment]
Will make some improvements to all form inputs soon. Thinking of doing a Quasar owned validation if I have enough free time.

**Comment by mariaczi** [comment]
@rstoenescu what is progress on that?
If you are going to develop own validation for Quasar, please remember to include ASYNC validation, as it is really important for e.g. uniqueness .

**Comment by rstoenescu** [comment]
Vee-validate seems the best option. Use that. Works with Vue 2 too.
Current plan is to add only a few CSS classes like for error.
Not sure it's worth it to duplicate work done by packages like vee-validate at this point.

**Comment by rstoenescu** [comment]
Go with `vee-validate` and use the new "has-error" CSS class for form components. This will land in next Quasar version after v0.8.2.

**Comment by murbanowicz** [comment]
@rstoenescu CSS `has-error` is not present in 0.8.3

**Comment by rstoenescu** [comment]
Yes, forgot to correct the statement. It will be available in v0.9.

**Comment by murbanowicz** [comment]
As I understand it will be applied to INPUT ?

Can you create a way to include error message below the input or you want to leave it to developers?

**Comment by rstoenescu** [comment]
There are so many ways to handle the error message.. there's no "generic" way to go. So I'll leave it to the developers.

**Comment by murbanowicz** [comment]
Just for future reference.

If you want to include errors under the input,

Apply something like:

```

.with-errors {
    height: 77px;
}

```

To not get so bad looking changing height of form to insert error message between fields.

**Comment by murbanowicz** [comment]
Just for future reference.

If you want to include errors under the input,

Apply something like:
```
.with-errors {
    height: 77px;
}
```

To not get so bad looking changing height of form to insert error message between fields.

**Comment by smolinari** [comment]
For those of you interested, I also found this library. 

https://github.com/monterail/vuelidate

Scott
